### ISSUE TITLE
Header icon issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Branko-Lazarevic-Speed-Work#1]
Bug - Search icon on header not visible.
Exp - Add search icon on header.
Ref link - https://drive.google.com/file/d/1GZevpQc-tSLlHN7uYd8hIyyp5G8prgAM/view

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/164231717-4fe99b30-733c-4462-ba7e-dd42f2328290.png)
![image](https://user-images.githubusercontent.com/89765850/164231801-353ee5d7-7d1a-471e-9a3a-d7b813427249.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
