### ISSUE TITLE
Club section on homepage UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Branko-Lazarevic-Speed-Work#2]
Bug - Club section on homepage have UI issue. button label breaking.
Exp - Button UI need to fix on cluc section on homepage.
Ref Link - https://drive.google.com/file/d/1LQef4t17HclQrhgB-Z8BFZ-I01RXVide/view

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/164231595-435138dd-2dea-4343-aa8f-33d75570d020.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
