### ISSUE TITLE
Footer section UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Branko-Lazarevic-Speed-Work#3]
Bug - Some links not shoiwng on footer and logo showing in center.
Exp - Add all navigations on footer and logo should be right aligned on footer.
Ref link - https://drive.google.com/file/d/1yKDEp-HVBqPCbo5x3Mon6xT_sQLZqe2Z/view

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/164231202-627130e2-7e27-44c9-a2ec-2080e3f83f2b.png)

**Comment by devAbhishekYadav** [comment]
after : 
![image](https://user-images.githubusercontent.com/89765850/164231427-f0cf3647-ccb9-4a4d-a9fd-cb9ba9676f78.png)

**Comment by ankitcedcoss** [comment]
Bug Fixed
