### ISSUE TITLE
Product page UI issue responsive - mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Branko-Lazarevic-Speed-Work#4]
Bug 1 - Product page padding not same on both end.
Bug 2 - Product image trimming on product page.
Exp :
- Fix padding issue on product page in responsive
- Prouduct image should not get trim.
Ref Link :
- https://drive.google.com/file/d/1ABQmK6kfrehvR-Pv7hVsbxZZg0vPFCIh/view
- https://drive.google.com/file/d/1yMGBWC3-rqoeXIhrtV5pFE7275aDdCP_/view

**Comment by devAbhishekYadav** [comment]
![image](https://user-images.githubusercontent.com/89765850/164231002-9a6f9444-25d6-4fe4-90da-70ee67e3b2f4.png)
resolved
